### PR TITLE
Switch from Travis and AppVeyor to GitHub Actions

### PR DESCRIPTION
**Pull request by jacobperron**
Same as https://github.com/colcon/colcon-gradle/pull/32

### CODE REVIEW

**Comment by jacobperron** [comment]
CI is blocked until we make a release of `colcon-gradle`.

**Review by esteve — APPROVED** [review]
Thanks! LGTM

**Comment by esteve** [comment]
@jacobperron can you add a badge similar to https://github.com/colcon/colcon-gradle/pull/34 Thanks.

**Comment by jacobperron** [comment]
I've added the badge in 4492aab

**Comment by jacobperron** [comment]
I guess the linters hadn't been run in a while. I work on addressing all of the failures.

**Review by ivanpauno — APPROVED** [review]
LGTM!

**Pull request merged**
