### PR TITLE
Add build task

### PR DESCRIPTION
**Pull request by Theosakamg**
Connected to https://github.com/colcon/colcon-ros/pull/30

### CODE REVIEW

**Comment by Theosakamg** [comment]
@esteve your feedback ?

**Comment by esteve** [comment]
Thanks. I've merged https://github.com/colcon/colcon-ros-gradle/commit/c5e4cf5ad5c34831efb2856241e58f0f82ae8585 which I think supersedes this PR, I got `rcljava_examples` built with my changes. I've tried to get your branch running, but I couldn't. Did manage to you build a package with your PR?

**Comment by esteve** [comment]
@Theosakamg any update? Are you ok with the changes in https://github.com/colcon/colcon-ros-gradle/commit/c5e4cf5ad5c34831efb2856241e58f0f82ae8585 ?

**Comment by Theosakamg** [comment]
@esteve You [close usage](https://github.com/colcon/colcon-ros-gradle/commit/c5e4cf5ad5c34831efb2856241e58f0f82ae8585#diff-5aa82c32cb7b8c36656fc04209c32a1eR70) to your gradle extention... (not very open for any alternative, but i understand) for the rest everything is ok

This PR no longer needs to exist so I'll close it.

**Pull request closed without merging**
