### PR TITLE
Return a str in which_executable()

### PR DESCRIPTION
**Pull request by ivanpauno**
See https://github.com/colcon/colcon-gradle/pull/35

### CODE REVIEW

**Review by cottsay — APPROVED** [review]
This is OK, but I'd rather see the conversion happen on line 49 so that `cmd` is always a `str` type.

**Comment by cottsay** [comment]
Side note - there is a lot of duplicated logic in this file. Looks like pretty much all of this could be imported from `colcon-gradle` instead of duplicated here.

**Comment by ivanpauno** [comment]
> This is OK, but I'd rather see the conversion happen on line 49 so that cmd is always a str type.

Done!

> Side note - there is a lot of duplicated logic in this file. Looks like pretty much all of this could be imported from colcon-gradle instead of duplicated here.

Yes, agreed.
Currently `colcon-ros-gradle` doesn't depend on `colcon-gradle`.
I can do that in a new PR if that sounds good to you.

**Comment by cottsay** [comment]
> Currently `colcon-ros-gradle` doesn't depend on `colcon-gradle`.

It actually does: https://github.com/colcon/colcon-ros-gradle/blob/fa7c6c092eadfd5cf0763074c7bc9b2b40766575/setup.cfg#L33

> I can do that in a new PR if that sounds good to you.

Absolutely - a separate PR would be best.

Thanks!

**Pull request merged**
